SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.TOTAL_PRICE AS TOTAL_SALES
FROM (
    SELECT B.AUTHOR_ID, B.CATEGORY, SUM(S.SALES*B.PRICE) AS TOTAL_PRICE
    FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
    WHERE MONTH(SALES_DATE) = 1 AND YEAR(SALES_DATE) = 2022
    GROUP BY B.AUTHOR_ID, B.CATEGORY
) B LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;

# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, SUM(TOTAL_PRICE) AS TOTAL_SALES
# FROM (
#     SELECT B.AUTHOR_ID, B.CATEGORY, S.SALES*B.PRICE AS TOTAL_PRICE
#     FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
#     WHERE MONTH(SALES_DATE) = 1 AND YEAR(SALES_DATE) = 2022
#     GROUP BY B.AUTHOR_ID, B.CATEGORY
# ) B LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
# ORDER BY AUTHOR_ID ASC, CATEGORY DESC;

# SELECT * FROM BOOK_SALES 
# WHERE BOOK_ID = 1 AND MONTH(SALES_DATE) = 1
# GROUP BY 

# SELECT B.AUTHOR_ID S.BOOK_ID, MONTH(S.SALES_DATE), S.SALES*B.PRICE AS TOTAL_PRICE
# FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
# WHERE MONTH(SALES_DATE) = 1
# GROUP BY MONTH(SALES_DATE)

# SELECT *, 
# COUNT(*) OVER(PARTITION BY AUTHOR_ID) AS GROUP_AUTHOR_ID
# FROM BOOK_SALES S LEFT JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
# WHERE MONTH(SALES_DATE) = 1 
# GROUP BY AUTHOR_ID, CATEGORY