SELECT C.CAR_ID, C.CAR_TYPE, FLOOR((1-D.DISCOUNT_RATE*0.01)*30*C.DAILY_FEE) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
RIGHT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND ((1-D.DISCOUNT_RATE*0.01)*30*C.DAILY_FEE BETWEEN 500000 AND 1999999) 
GROUP BY CAR_ID
HAVING (MIN(START_DATE) > '2022-11-30' OR MAX(END_DATE) < '2022-11-01') 
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC