SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, H.START_DATE, H.END_DATE
FROM CAR_RENTAL_COMPANY_CAR C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_CAR
                WHERE CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
AND DATE_FORMAT(H.START_DATE, "%Y-%m-%d") > '2022-11-30' OR DATE_FORMAT(H.END_DATE, "%Y-%m-%d") < '2022-11-01'

# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY