WITH RECURSIVE ECOLI AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ED.ID, ED.PARENT_ID, ECOLI.GENERATION+1
    FROM ECOLI JOIN ECOLI_DATA ED ON ECOLI.ID = ED.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM ECOLI
WHERE ID NOT IN (
    SELECT DISTINCT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL
    )
GROUP BY GENERATION
ORDER BY GENERATION ASC;