# SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(AMOUNT) AS TOTAL_SALES
# FROM FOOD_ORDER O INNER JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
# WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
# GROUP BY O.PRODUCT_ID
# ORDER BY SUM(AMOUNT) DESC, P.PRODUCT_ID ASC

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(AMOUNT)*(SELECT PRICE FROM FOOD_PRODUCT WHERE PRODUCT_ID = P.PRODUCT_ID) AS TOTAL_SALES
FROM FOOD_ORDER O INNER JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY PRODUCT_ID
ORDER BY SUM(AMOUNT)*(SELECT PRICE FROM FOOD_PRODUCT WHERE PRODUCT_ID = P.PRODUCT_ID) DESC, P.PRODUCT_ID ASC
